# Generated by Django 4.0.3 on 2022-03-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('surname', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=250)),
                ('bidding_settings', models.CharField(max_length=250)),
                ('google_id', models.IntegerField()),
            ],
        ),
    ]
