# Generated by Django 4.0.3 on 2022-03-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userData',
            new_name='Account',
        ),
    ]
