# Generated by Django 4.0.3 on 2022-03-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_rename_userdata_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='dob',
            new_name='d_o_b',
        ),
    ]
