# Generated by Django 4.0.3 on 2022-03-14 08:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_rename_dob_account_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='bidding_settings',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='d_o_b',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
